### ISSUE TITLE
Pop out button for VZ Quick-Code

### ISSUE THREAD

**Issue by ThePrimoris** [vizality/community#8]
**Description**
Pop out button in VZ Dashboard's Quick-Code

**Expected behavior**
Click the button and it inputs the code into the console and pops out the quick-code.

**Additional context**
[Screenshot](https://i.imgur.com/1LOjjIN.png)

----

- [X] I have checked to make sure a similar request has not already been proposed
- [X] I have checked to made sure this request complies with Vizality's [guidelines](https://github.com/vizality/community/blob/main/GUIDELINES.md)

**Comment by valentinegb** [comment]
I feel like this would be better as a feature, not a plugin. 🤔

**Comment by dperolio** [comment]
Yeah, definitely. This will be an in-built feature, soon™.
